build_from:
  aarch64: "ghcr.io/linuxserver/baseimage-alpine:arm64v8-3.22"
  amd64: "ghcr.io/linuxserver/baseimage-alpine:amd64-3.22"
#  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
#  amd64: "ghcr.io/home-assistant/amd64-base:latest"
labels:
  org.opencontainers.image.title: "qBittorrent addon with wireguard"
  org.opencontainers.image.description: "qBittorrent addon with wireguard"
  org.opencontainers.image.source: "https://github.com/nyok92/hassio-addons-test/qbittorrent-wireguard"
  org.opencontainers.image.licenses: "GNU General Public License v3.0"
#args:
#   QBT_CLI_VERSION: v1.8.24285.1
#  codenotary: yes
#  codenotary.base_image: notary@home-assistant.io
