build_from:
  aarch64: "ghcr.io/linuxserver/baseimage-alpine:arm64v8-3.22"
  amd64: "ghcr.io/linuxserver/baseimage-alpine:amd64-3.22"
labels:
  org.opencontainers.image.title: "qBittorrent addon with wireguard"
  org.opencontainers.image.description: "qBittorrent addon with wireguard"
  org.opencontainers.image.source: "https://github.com/nyok92/hassio-addons-test/qbittorrent-wireguard"
  org.opencontainers.image.licenses: "GNU General Public License v3.0"
